apiVersion: v1
kind: Pod
metadata:
  name: phi2-pod
  labels:
    app: phi2
spec:
  containers:
  - name: phi2-container
    image: ollama/ollama:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        ollama serve &
        sleep 5
        ollama pull phi
        ollama run phi
        tail -f /dev/null
    resources:
      requests:
        memory: "16Gi"
        cpu: "8"
      limits:
        memory: "24Gi"
        cpu: "12"
    env:
      - name: OLLAMA_HOST
        value: "0.0.0.0:11435"
      - name: OLLAMA_ORIGINS
        value: "*"
      - name: OLLAMA_MODELS
        value: "/root/.ollama/models"
      - name: OLLAMA_KEEP_ALIVE
        value: "5m"
      - name: OLLAMA_NUM_THREAD
        value: "4"
      - name: OLLAMA_NUM_CTX
        value: "2048"
      - name: OLLAMA_BATCH_SIZE
        value: "512"
      - name: OLLAMA_NEW_ENGINE
        value: "true"
      - name: OLLAMA_FLASH_ATTENTION
        value: "false"
      - name: OLLAMA_LOAD_TIMEOUT
        value: "60s"
    ports:
    - containerPort: 11435
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: phi2
spec:
  selector:
    app: phi2
  ports:
    - protocol: TCP
      port: 11435
      targetPort: 11435
  type: ClusterIP 