apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-watcher-binding
subjects:
  - kind: ServiceAccount
    name: event-watcher-sa
    namespace: default  # Change if your SA is in a different namespace
roleRef:
  kind: ClusterRole
  name: event-watcher-role
  apiGroup: rbac.authorization.k8s.io